ORG 100H

.MODEL SMALL
.STACK 100H

.DATA
STR DB 100 DUP('$')   ; RESERVE 100 BYTES FOR STRING STORAGE, INITIALIZED WITH '$'

.CODE
MAIN PROC
    MOV AX, @DATA      ; INITIALIZE DATA SEGMENT
    MOV DS, AX

    ; ---------- INPUT LOOP ----------
    LEA SI, STR        ; LOAD ADDRESS OF STR INTO SI
INPUT_LOOP:
    MOV AH, 1          ; SERVICE TO READ CHARACTER FROM KEYBOARD
    INT 21H
    CMP AL, 13         ; CHECK IF ENTER (CARRIAGE RETURN) IS PRESSED
    JE DONE_INPUT      ; IF ENTER, END INPUT
    MOV [SI], AL       ; STORE CHARACTER IN STR[SI]
    INC SI             ; MOVE TO NEXT CHARACTER
    JMP INPUT_LOOP     ; CONTINUE LOOP

DONE_INPUT:
    MOV AH, 2
    MOV DL, 10         ; NEW LINE (LINE FEED)
    INT 21H
    MOV DL, 13         ; CARRIAGE RETURN
    INT 21H

    ; ---------- PRINT STRING ----------
    LEA DX, STR        ; LOAD ADDRESS OF STR INTO DX
    MOV AH, 9          ; SERVICE TO PRINT STRING UNTIL '$'
    INT 21H

    ; ---------- EXIT PROGRAM ----------
    MOV AH, 4CH        ; TERMINATE PROGRAM
    INT 21H
MAIN ENDP
END MAIN
